/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesDay01RouteImport } from './routes/pages/day-01'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDay01Route = PagesDay01RouteImport.update({
  id: '/pages/day-01',
  path: '/pages/day-01',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/day-01': typeof PagesDay01Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/day-01': typeof PagesDay01Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/day-01': typeof PagesDay01Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/day-01'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/day-01'
  id: '__root__' | '/' | '/pages/day-01'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesDay01Route: typeof PagesDay01Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/day-01': {
      id: '/pages/day-01'
      path: '/pages/day-01'
      fullPath: '/pages/day-01'
      preLoaderRoute: typeof PagesDay01RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesDay01Route: PagesDay01Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
